remove illegal a-element attributes
i.e. ones that make the resulting XML document non-well-formed:

    xml.etree.ElementTree.ParseError: not well-formed (invalid token):
        line 4485, column 8

Basically because something like

    <a href="/Articles/718632/"</a>this article</a>

is parsed by html5lib (and even Firefox 57) into something like:

    <html:a <="" a="" href="https://lwn.net/Articles/718632/">this article</html:a>

Example input from: https://lwn.net//Articles/744047/